### ISSUE TITLE
Password reset not working

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#50] opened 2016-01-25 22:51 UTC
On 21 January 2016 at 08:09, Frazer Kirkman frazer@frazerk.net wrote:
Hi,

after requesting a password reset, receiving the email and clicking on the the link in that email, I am taken to a page that says:

The page you requested does not exist

on  http://effective-altruism.com/resetpassword/abcasgfrg

**Comment by tog22** [comment] 2016-01-25 22:52
@arichard4 are you free to look at this, and reply to Frazer ccing Peter as appropriate?

**Comment by arichard4** [comment] 2016-01-27 00:13
Yeah, will do.

**Comment by tog22** [comment] 2016-01-29 02:33
:heart: Alex

**Comment by patbl** [comment] 2016-02-07 20:36
The password-reset URL that you get in the e-mail works for only one form submission. You get the "does not exist" error if you use the link after you submit the form. It would be nice to have a more informative message ("That password-reset link has expired. Click here to request a new one.").

I'm not sure whether Frazer was trying to use an expired link or whether there's a bug. I'll ask him what happens if he tries again.

**Comment by patbl** [comment] 2016-02-07 20:39
There does seem to be another bug to do with resetting passwords: After you submit the form, you are logged in, but the message that's displayed is "Your session has expired."

![your-session-has-expired](https://cloud.githubusercontent.com/assets/1735266/12875108/cd05e456-cd97-11e5-856e-61b6ad7ad48f.png)

**Comment by tog22** [comment] 2016-02-08 18:44
Thanks for contacting Frazer Patrick

**Comment by peterhurford** [comment] 2016-04-02 23:22
@tog22 @patbl Did this ever get fixed?

**Comment by patbl** [comment] 2016-04-03 01:53
No. I couldn't reproduce the bug. I'll contact Frazer again.

**Comment by tog22** [comment] 2016-04-09 15:36
Great, thanks! What did he say?

On 2 April 2016 at 18:53, Patrick Brinich-Langlois <notifications@github.com

> wrote:
> 
> No. I couldn't reproduce the bug. I'll contact Frazer again.
>

**Comment by patbl** [comment] 2016-04-09 16:28
He didn't respond. Maybe we should close this if no one else has reported it.

**Comment by tog22** [comment] 2016-04-09 16:31
Sure, just reopen if it he does reply.

On 9 April 2016 at 09:28, Patrick Brinich-Langlois <notifications@github.com

**Comment by patbl** [comment] 2016-04-17 04:16
Frazer got back to me. Here's a more-detailed account of his problem. I'll investigate soon (50% chance by tomorrow).

![screenshot 2016-04-16 21 14 14](https://cloud.githubusercontent.com/assets/1735266/14585024/760106b0-0418-11e6-9e45-8a5e7c53f30a.png)

**Comment by patbl** [comment] 2016-04-17 17:38
It would probably be worth fixing the "Your session has expired" message. I'll work on that.

Frazer tried changing his password, and apparently it didn't update. So there may be an additional, more-subtle bug. But I haven't been able to reproduce it, so I'll set that aside for now.

**Comment by peterhurford** [comment] 2016-04-26 23:52
@patbl Any updates on being able to reproduce? Any other things to do here? Otherwise we can close.

**Comment by patbl** [comment] 2016-04-27 00:07
I tried to fix one of the issues (showing "Your session has expired" after you successfully reset your password) [here](https://github.com/tricycle/eaforum/pull/36).

It's not a big deal, but I think I should verify that this fix and the ones in my other pull requests work on production before we close the issues—leaving them open makes me somewhat less likely to forget to do this.

I wasn't able to reproduce Frazer's other bug, which was that when he seemingly successfully submitted a new password, it wasn't updated (it didn't work if he logged out and logged in again).

**Comment by peterhurford** [comment] 2016-04-27 00:07
@patbl Cool, if you can verify https://github.com/tricycle/eaforum/pull/36 I think we can close this.

**Comment by tog22** [comment] 2016-05-06 20:44
Good idea, let's make that the policy for closing issues from now on

**Comment by patbl** [comment] 2016-05-12 04:07
You no longer see "Your session has expired" after resetting a password.

**Closed as completed by patbl** 2016-05-12 04:07 UTC
Labels: high priority, medium difficulty
