### ISSUE TITLE
Duplicate upcoming events

### ISSUE THREAD

**Issue by RyanCarey** [tog22/eaforum#29] opened 2015-08-07 17:30 UTC
Hey,

A user Gina Stuessy has pointed out to me that meetups appear to be going up twice recently. Any ideas why this might be?

![image](https://cloud.githubusercontent.com/assets/8340923/9141641/2bfb3b88-3d32-11e5-984f-fdfe2f1dcc92.png)

**Comment by tog22** [comment] 2015-08-07 18:54
@peterhurford and I will (get someone to) fix this.

**Comment by arichard4** [comment] 2015-08-07 21:49
1) If you look at all meetups, it looks like every meetup is now being duplicated. (There's one weird very old meetup on that page.)
2) They are different entries in the system; they lead to different URLs.
3) At least for me, both links are broken; i.e. meetups are now almost totally nonfunctional.
4) Going to /r/meetups, it looks like no new meetups have been created since July 21st.
5) I just made a new meetup; it is not duplicated on the upcoming meetups page, but doesn't show up on /r/meetups and is a broken link.

I think that the meetups might not actually be getting duplicated; people are just submitting them twice. (Or, at least, I can't duplicate this.) We should add a redirect or better message to let people know that the meetup has been submitted. Also, the current 'submitted' message shows on page load, then goes away on submission, which is the opposite of how it should be.

The broken links is a different, and weirder, problem. I have no explanation of it right now.

**Comment by tog22** [comment] 2015-08-12 01:06
What's the meetup you made @arichard4 ?

**Comment by tog22** [comment] 2015-08-12 01:06
@RyanCarey would you like us to temporarily hide meetups if this looks like it'll take a while to fix?

**Comment by arichard4** [comment] 2015-08-12 03:08
It was for the Stanford EA meeting Sunday, which has already occurred. I've made another for next Sunday; it also appears to not be duplicated and has a broken link.

**Comment by RyanCarey** [comment] 2015-08-12 09:47
@tog22: up to you

Ryan Carey | bioinformatics student | medical resident

**Comment by arichard4** [comment] 2015-08-14 13:59
The Stanford EA meetup I posted is still not duplicated, at least to me; there is another meetup that is posted three times (triplicated)

**Comment by tog22** [comment] 2015-08-14 20:46
@RyanCarey OK I'll leave it for now, _partly_ because Trike will be slow to update it.

@arichard4 I had someone else test this - I still need to pin them down on what happened, but they said " it only said submitting and never went to new page" so I expect that's leading people to resubmit. And of course there's still the issue that click on all meetups gives an error message (the one we discussed in https://github.com/tog22/eaforum/issues/30 ). I replied to your comments on resolving it on Slack.

**Comment by tog22** [comment] 2015-08-14 22:26
I've posted a standard 'here's a problem, we're aware of it' message on the Forum: http://effective-altruism.com/ea/me/housekeeping_notice_the_meetups_sidebar_is/

**Comment by arichard4** [comment] 2015-08-16 19:59
I've just gotten my local meetups version working again, by restarting the vagrant box. Here's the error traceback for trying to access the meetup page:

<pre>Module r2.controllers.validator.validator:78 in newfn         
>>  return fn(self, *a, **kw)
Module r2.controllers.meetupscontroller:176 in GET_show         
>>  article = Link._byID(meetup.assoc_link)
Module r2.lib.db.thing:497 in __getattr__         
>>  return DataThing.__getattr__(self, attr)
Module r2.lib.db.thing:124 in __getattr__         
>>  raise AttributeError, '%s not found' % attr
<type 'exceptions.AttributeError'>: assoc_link not found</pre>

The meetups are being created in the database.

**Comment by arichard4** [comment] 2015-08-18 21:04
Playing around on the server error screen, it looks like assoc_link genuinely isn't being generated; the table reddit_data_meetup doesn't include assoc_link for any of the three meetups. MeeetupsController.py commits newly created meetups to the db twice; the full code is here:

```
meetup = Meetup(
  author_id = c.user._id,

  title = title,
  description = description,

  location = location,
  latitude = latitude,
  longitude = longitude,

  timestamp = timestamp,
  tzoffset = tzoffset
)

# Expire all meetups in the render cache
g.rendercache.invalidate_key_group(Meetup.group_cache_key())

meetup._commit()

l = Link._submit(meetup_article_title(meetup), meetup_article_text(meetup),
                 c.user, Subreddit._by_name('meetups'),ip, [])

l.meetup = meetup._id36
l._commit()
meetup.assoc_link = l._id
meetup._commit()
```

It's possible that the second commit is failing silently; that _commit doesn't know to commit .assoc_link; that Link._submit is returning something broken which fails silently; or something else. Because this is a backend problem, it will require recompiling r2 to fix. I also still don't understand what would cause this to work in the past and then stop working.

**Comment by tog22** [comment] 2015-08-18 22:14
Thanks for trying to get to the bottom of this Alex! Say if you want me to get Trike to do anything, such as recompiling r2.

**Comment by arichard4** [comment] 2015-08-23 22:21
Update:
In the above section of code, the error is located within the line 
l = Link._submit(meetup_article_title(meetup), meetup_article_text(meetup),
                 c.user, Subreddit._by_name('meetups'),ip, [])

Here's the full traceback:

<pre>Module r2.lib.jsonresponse:181 in _Json         
>>  val = func(self, res, *a, **kw)
Module r2.controllers.validator.validator:78 in newfn         
>>  return fn(self, *a, **kw)
Module r2.controllers.meetupscontroller:93 in POST_create         
>>  l = Link._submit(meetup_article_title(meetup), meetup_article_text(meetup),
Module r2.controllers.meetupscontroller:22 in meetup_article_text         
>>  res = t.get_def("meetup_info").render_unicode(meetup=meetup)
Module mako.template:452 in render_unicode         
>>  as_unicode=True)
Module mako.runtime:803 in _render         
>>  **_kwargs_for_callable(callable_, data))
Module mako.runtime:839 in _render_context         
>>  _exec_template(callable_, context, args=args, kwargs=kwargs)
Module mako.runtime:860 in _exec_template         
>>  callable_(context, *args, **kwargs)
Module r2_templates_showmeetup_html:113 in render_meetup_info         
Module r2_templates_showmeetup_html:25 in _mako_get_namespace         
Module r2_templates_showmeetup_html:28 in _mako_generate_namespaces         
Module mako.runtime:546 in __init__         
>>  calling_uri)
Module mako.runtime:766 in _lookup_template         
>>  context._with_template.uri)
<type 'exceptions.AttributeError'>: 'DefTemplate' object has no attribute 'uri' </pre>

This results in the first commit succeeding, showing everybody the meetup (e.g. on the sidebar and the page); but it doesn't get actually written to /r/meetups and there is no valid post to link to.

**Comment by tog22** [comment] 2015-08-24 02:04
@arichard4:

Looks like some progress! I imagine it's tough, but can you _estimate_ when you'd expect this to be fixed? If it's some way off I think I maybe should disable meetups in the sidebar after all?

**Comment by arichard4** [comment] 2015-08-24 20:57
The problem is caused by my changes to showmeetup.html for implementing profile links; reverting them fixes it

**Comment by RyanCarey** [comment] 2015-09-08 17:52
New error - when I click Petrov Day meetup, I get this: http://effective-altruism.com/meetups/3r:
"Error encountered

You have encountered an error in the code that runs Less Wrong. The site maintainers have been informed and will get to it is as soon as they can.

In the unlikely event that you've bumped into this error before and think that no-one is paying attention, please report the error and how to reproduce it on http://code.google.com/p/lesswrong/issues/list'

If the error is localised you might still find awesome Less Wrong content in the Main article area or in the Discussion area."

**Comment by arichard4** [comment] 2015-09-09 18:02
That's the same as the old error- the meetups are not getting created correctly in the db. The above change appears to fix it.

The incorrect server error message is issue #30, for which I've also submitted a fix.

**Comment by peterhurford** [comment] 2015-09-15 19:11
Submitted to Trike as https://github.com/tricycle/eaforum/pull/18

**Comment by tog22** [comment] 2015-09-17 18:12
The PR's merged (allegedly) but the error persists, I just tested it by making http://effective-altruism.com/meetups/3v . Though the error message there hasn't changed either, suggesting the PRs may not actually be deployed?

**Comment by peterhurford** [comment] 2015-09-22 19:45
The PR was deployed, so the error must be persisting.  @arichard4 can you look at it?  Or are you busy again with school?

**Comment by arichard4** [comment] 2015-09-27 21:31
Sorry, was busy starting school
The issue is that the PR for some reason didn't actually update Trike's version to match the version on tog22; you can see this by comparing them now:

Trike's version still has the line importing userlink_profile from utils at the start, which is the line breaking meetups:
https://github.com/tricycle/eaforum/blob/master/r2/r2/templates/showmeetup.html

The version on here has that line properly removed:
https://github.com/tog22/eaforum/blob/master/r2/r2/templates/showmeetup.html

The PR seemed to update everything on Trike's repo correctly except for that, but didn't touch that line:
https://github.com/tricycle/eaforum/pull/18/files

**Closed as completed** 2015-10-04 19:56 UTC
Labels: high priority, medium difficulty

**Comment by tog22** [comment] 2015-10-06 19:20
:heart: :heart: :heart:
