### ISSUE TITLE
Stop HTML comments showing in post previews

### ISSUE THREAD

**Issue by tog22** [tog22/eaforum#67] opened 2016-07-08 20:26 UTC
When there are HTML comments `<!-- like this -->` in the first few lines of a post, they show up in the preview on the front page at http://effective-altruism.com/ . They'd need filtering out for this.

**Comment by tog22** [comment] 2016-07-08 20:27
Would you be OK to do this @arichard4 ?

**Comment by tog22** [comment] 2016-07-08 20:27
(No worries if not obviously! What's your general availability for tech work these days.)

**Comment by arichard4** [comment] 2016-07-08 22:07
I start fulltime work Monday.
So not so good.

**Comment by tog22** [comment] 2016-07-23 03:58
Gotcha! @patbl, would be great if you could try this when you have a chance!

**Comment by patbl** [comment] 2016-07-24 07:19
Sure. I tried the following in dev and couldn't reproduce the issue:

```
<!--lol test -->
<p>rstrst</p>
<!-- like this -->
<p>huh what?</p>
```

If you have access to a post with this problem, could you send me a link, or the HTML itself (if it was your post)?

**Comment by patbl** [comment] 2016-08-25 03:47
@tog22 Do you have an example?

**Comment by tog22** [comment] 2016-09-01 13:46
Sure, see 'Help SHIC Get Off The Ground' at http://effective-altruism.com/user/Tom_Ash/ . By the way, I'm stepping back from .impact work so won't be dealing with its EA Forum work from now on - I've asked Georgie Mallett (the new manager of .impact) and Peter to say who the best person to tag is (it may revert to @peterhurford for a while).

**Comment by peterhurford** [comment] 2016-09-05 21:05
Here's an example:

![](https://puu.sh/r19KL/2f4d36ba54.png)

**Comment by patbl** [comment] 2016-10-05 05:14
Fixed by tricycle/eaforum#51.

**Closed as completed by patbl** 2016-10-05 05:14 UTC
Labels: medium priority, medium difficulty
